#!/usr/bin/env python3
"""Generate en/index.html from index.html.

index.html is the single source: every piece of text carries both languages
(<span class="zh">…</span><span class="en" lang="en">…</span>) and <html lang>
decides which one is shown. This script writes the English entry point —
the same document with lang="en", an English <head> (title, description,
share card, structured data) and English static labels — so that
https://datou.fm/en/ has its own URL.

    python3 tools/build-en.py          # (re)generate en/index.html
    python3 tools/build-en.py --check  # exit 1 if en/index.html is stale

Run it after every edit to index.html and commit both files.
Only the Python 3 standard library is used.
"""
import html, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'index.html')
DST = os.path.join(ROOT, 'en', 'index.html')

# English search / share metadata. The page <title> itself is NOT here: it is read
# from the JS title table in index.html so it exists exactly once.
EN = {
    'description': ('Datou FM (大头会) is a Mandarin-language podcast by three Oxford MBA classmates in three cities: '
                    'long conversations about AI, business, investing, and China. Episode notes in English.'),
    'og_description': ('A Mandarin podcast by three Oxford MBA classmates in three cities: long conversations about AI, '
                       'business, investing, and China. Episode notes in English.'),
    'site_name': 'Datou FM 大头会',
    'rss_title': 'Datou FM Podcast RSS',
    'series_description': ('Datou FM (大头会) is a Mandarin-language podcast hosted by three Oxford MBA classmates in three cities, '
                           'about AI, business, investing, and China. 《大头会》是一档由三位牛津大学MBA同班同学主持的中文播客。'),
}
# static landmark labels: Chinese in index.html, swapped here from the DATOU string table
# (the JS re-labels them at runtime from the same table)
LANDMARKS = [('nav class="top"', 'sections'), ('nav class="lang"', 'langnav'),
             ('nav class="tabbar"', 'tabbar'), ('section class="books"', 'books')]
DOCK_KEYS = ['player', 'pp', 'seek', 'back', 'fwd', 'mute', 'vol', 'speed', 'close']

BANNER = ('<!-- GENERATED by tools/build-en.py from index.html — do not edit this file; '
          'edit index.html and run the script. -->\n')


def one(pattern, repl, text, flags=0, count=1):
    """Replace exactly `count` matches; the replacement is literal text, never a template."""
    new, n = re.subn(pattern, repl if callable(repl) else (lambda _m: repl), text, count=count, flags=flags)
    if n != count:
        sys.exit(f'build-en: expected {count} match(es), found {n}: {pattern[:80]}')
    return new


def inner_text(fragment):
    """Visible text of an HTML fragment (tags dropped, entities decoded, spaces collapsed)."""
    return re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', ' ', fragment))).strip()


def js_unescape(s):
    """Decode a single-quoted JS string literal's escapes."""
    return re.sub(r"\\(u[0-9a-fA-F]{4}|.)",
                  lambda m: chr(int(m.group(1)[1:], 16)) if m.group(1)[0] == 'u'
                  else {'n': '\n', 't': '\t'}.get(m.group(1), m.group(1)), s)


def js_title(src, lang):
    """titles.<lang>.podcast from the router's title table."""
    m = re.search(r"\b%s: \{\s*podcast: '((?:[^'\\]|\\.)*)'" % lang, src)
    if not m:
        sys.exit(f'build-en: titles.{lang}.podcast not found in index.html')
    return js_unescape(m.group(1))


def js_strings(src, lang):
    """The DATOU string table for one language: {key: text}."""
    m = re.search(r"\b%s: \{(.*?)\},?\n" % lang, src, re.S)
    if not m:
        sys.exit(f'build-en: DATOU strings for {lang} not found in index.html')
    return {k: js_unescape(v) for k, v in re.findall(r"(\w+): '((?:[^'\\]|\\.)*)'", m.group(1))}


def episodes_en(doc):
    """{mp3 url: (english title, chinese title, english notes, english dock title)} from the article cards."""
    out = {}
    for m in re.finditer(r'<article class="episode[^"]*" data-audio="([^"]+)"([^>]*)>(.*?)</article>', doc, re.S):
        audio, attrs, body = m.group(1), m.group(2), m.group(3)
        dock = re.search(r'data-title-en="([^"]*)"', attrs)
        h3 = re.search(r'<h3>\s*<span class="zh"[^>]*>(.*?)</span>\s*<span class="en" lang="en"[^>]*>(.*?)</span>\s*</h3>', body, re.S)
        desc = re.search(r'<p class="desc en" lang="en"[^>]*>(.*?)</p>', body, re.S)
        if not (h3 and desc and dock):
            sys.exit(f'build-en: episode card for {audio} lacks an English title, notes or data-title-en')
        zh = re.sub(r'^\d{3}｜', '', inner_text(h3.group(1)))
        en_html = re.sub(r'<span class="t-num">\d{3}</span>', '', h3.group(2))
        en_html = en_html.replace('<span class="t-guest">', ' | ')
        out[audio] = (inner_text(en_html), zh, inner_text(desc.group(1)), html.unescape(dock.group(1)))
    return out


def build(src):
    # the two copies of each page title must agree (showView() rewrites document.title on load)
    static_zh = html.unescape(re.search(r'<title>(.*?)</title>', src, re.S).group(1))
    if js_title(src, 'zh') != static_zh:
        sys.exit('build-en: titles.zh.podcast differs from the static <title> in index.html')
    en_title = js_title(src, 'en')
    S_zh, S_en = js_strings(src, 'zh'), js_strings(src, 'en')

    doc = src
    doc = one(r'<html lang="zh-CN">', '<html lang="en">', doc)
    doc = one(r'<!DOCTYPE html>[ \t]*\n', lambda m: m.group(0) + BANNER, doc, flags=re.I)
    doc = one(r'<title>.*?</title>', '<title>' + html.escape(en_title, quote=False) + '</title>', doc, re.S)
    doc = one(r'<meta name="description" content="[^"]*" />',
              '<meta name="description" content="%s" />' % html.escape(EN['description']), doc)
    doc = one(r'<link rel="canonical" href="https://datou.fm/" />',
              '<link rel="canonical" href="https://datou.fm/en/" />', doc)
    doc = one(r'<meta property="og:site_name" content="[^"]*" />',
              '<meta property="og:site_name" content="%s" />' % html.escape(EN['site_name']), doc)
    doc = one(r'<meta property="og:title" content="[^"]*" />',
              '<meta property="og:title" content="%s" />' % html.escape(en_title), doc)
    doc = one(r'<meta property="og:description" content="[^"]*" />',
              '<meta property="og:description" content="%s" />' % html.escape(EN['og_description']), doc)
    doc = one(r'<meta property="og:url" content="https://datou.fm/" />',
              '<meta property="og:url" content="https://datou.fm/en/" />', doc)
    doc = one(r'<meta property="og:locale" content="zh_CN" />\n<meta property="og:locale:alternate" content="en_US" />',
              '<meta property="og:locale" content="en_US" />\n<meta property="og:locale:alternate" content="zh_CN" />', doc)
    doc = one(r'<meta name="twitter:title" content="[^"]*" />',
              '<meta name="twitter:title" content="%s" />' % html.escape(en_title), doc)
    doc = one(r'<meta name="twitter:description" content="[^"]*" />',
              '<meta name="twitter:description" content="%s" />' % html.escape(EN['og_description']), doc)
    doc = one(r'<link rel="alternate" type="application/rss\+xml" title="[^"]*"',
              '<link rel="alternate" type="application/rss+xml" title="%s"' % html.escape(EN['rss_title']), doc)

    # structured data: same series (@id), English names, Chinese kept as alternateName,
    # inLanguage stays zh-CN because the audio is Mandarin
    m = re.search(r'<script type="application/ld\+json">\n(.*?)\n</script>', doc, re.S)
    if not m:
        sys.exit('build-en: JSON-LD block not found')
    data = json.loads(m.group(1))
    eps = episodes_en(doc)
    ld_urls = {n['associatedMedia']['contentUrl'] for n in data['@graph'] if n['@type'] == 'PodcastEpisode'}
    if ld_urls != set(eps):
        sys.exit('build-en: cards and JSON-LD list different episodes: ' + repr(sorted(ld_urls ^ set(eps))))
    for node in data['@graph']:
        if node['@type'] == 'PodcastSeries':
            node['name'] = 'Datou FM'
            node['alternateName'] = ['大头会', 'datou.fm']
            node['description'] = EN['series_description']
            if isinstance(node.get('publisher'), dict):
                node['publisher']['name'] = EN['site_name']
        elif node['@type'] == 'PodcastEpisode':
            en_name, zh_name, en_desc, _ = eps[node['associatedMedia']['contentUrl']]
            if zh_name != node['name']:
                sys.exit(f'build-en: JSON-LD name differs from the card title:\n  {node["name"]}\n  {zh_name}')
            node['name'] = en_name
            node['alternateName'] = zh_name
            node['description'] = en_desc
            node['url'] = 'https://datou.fm/en/#episodes'
    doc = doc[:m.start(1)] + json.dumps(data, ensure_ascii=False, indent=2) + doc[m.end(1):]

    # static labels the JS would otherwise correct only after it runs
    for sel, key in LANDMARKS:
        doc = one(r'<%s aria-label="%s">' % (re.escape(sel), re.escape(S_zh[key])),
                  '<%s aria-label="%s">' % (sel, html.escape(S_en[key])), doc)
    doc = one(re.escape('data-lang="zh" aria-current="true">中文'), 'data-lang="zh">中文', doc, count=2)
    doc = one(re.escape('data-lang="en">English'), 'data-lang="en" aria-current="true">English', doc, count=2)
    for key in DOCK_KEYS:
        zh, en = S_zh[key], S_en[key]
        n = 2 if key == 'speed' else 1
        if key == 'speed':
            doc = one(r'aria-label="%s 1X"' % re.escape(zh), 'aria-label="%s 1X"' % html.escape(en), doc)
        doc = one(r'aria-label="%s"' % re.escape(zh), 'aria-label="%s"' % html.escape(en), doc, count=n - (1 if key == 'speed' else 0))
    for audio, (_, _, _, dock_title) in eps.items():
        block = re.search(r'<article class="episode[^"]*" data-audio="%s".*?</article>' % re.escape(audio), doc, re.S)
        fixed = one(r'aria-label="%s [^"]*"' % re.escape(S_zh['play'].strip()),
                    'aria-label="%s%s"' % (html.escape(S_en['play']), html.escape(dock_title)), block.group(0))
        doc = doc[:block.start()] + fixed + doc[block.end():]

    # hidden-language text: on /en/ the Chinese is the hidden half — mark it so screen
    # readers treat it as Chinese and search engines don't quote it. data-nosnippet is
    # honoured on span/div/section, so paragraphs get an inner wrapper instead of the attribute.
    doc, n_unwrap = re.subn(r'(<p\b[^>]*\bclass="[^"]*\ben\b[^"]*"[^>]*>)<span data-nosnippet>(.*?)</span>(</p>)', r'\1\2\3', doc, flags=re.S)
    doc = doc.replace(' data-nosnippet>', '>')
    if ' data-nosnippet' in doc:
        sys.exit('build-en: a data-nosnippet mark survived in an unexpected place')
    def with_lang(tag):
        return tag if ' lang=' in tag else tag[:-1] + ' lang="zh-CN">'
    doc, n_p = re.subn(r'(<p\b[^>]*\bclass="[^"]*\bzh\b[^"]*"[^>]*>)(.*?)(</p>)',
                       lambda m: with_lang(m.group(1)) + '<span data-nosnippet>' + m.group(2) + '</span>' + m.group(3), doc, flags=re.S)
    doc, n_other = re.subn(r'<(?!p\b)[a-zA-Z][\w-]*\b[^>]*\bclass="[^"]*\bzh\b[^"]*"[^>]*>',
                           lambda m: with_lang(m.group(0))[:-1] + ' data-nosnippet>', doc)
    want = len(re.findall(r'\bclass="[^"]*\bzh\b[^"]*"', doc))
    if n_p + n_other != want:
        sys.exit(f'build-en: marked {n_p + n_other} .zh elements but found {want} class="…zh…" attributes')
    return doc


def main():
    args = sys.argv[1:]
    if args in (['-h'], ['--help']):
        print(__doc__.strip())
        return
    if args not in ([], ['--check']):
        sys.exit(f'build-en: unknown argument(s) {args!r}\nusage: python3 tools/build-en.py [--check]')
    src = open(SRC, encoding='utf-8').read()
    if 'GENERATED by tools/build-en.py' in src:
        sys.exit('build-en: index.html looks like a generated file')
    out = build(src)
    if args:
        cur = open(DST, encoding='utf-8').read() if os.path.exists(DST) else ''
        if cur != out:
            sys.exit('build-en: en/index.html is stale — run python3 tools/build-en.py')
        print('build-en: en/index.html is up to date')
        return
    os.makedirs(os.path.dirname(DST), exist_ok=True)
    open(DST, 'w', encoding='utf-8').write(out)
    print(f'build-en: wrote en/index.html ({len(out):,} bytes, {len(episodes_en(src))} episodes)')


if __name__ == '__main__':
    main()
